services:
  joomla:
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
    restart: always
    ports:
      - 8030:80
    environment:
      JOOMLA_DB_HOST: ${JOOMLA_DB_HOST}
      JOOMLA_DB_USER: ${JOOMLA_DB_USER}
      JOOMLA_DB_PASSWORD: ${JOOMLA_DB_PASSWORD}
      JOOMLA_DB_NAME: ${JOOMLA_DB_NAME}
      JOOMLA_SITE_NAME: ${JOOMLA_SITE_NAME}
      JOOMLA_ADMIN_USER: ${JOOMLA_ADMIN_USER}
      JOOMLA_ADMIN_USERNAME: ${JOOMLA_ADMIN_USERNAME}
      JOOMLA_ADMIN_PASSWORD: ${JOOMLA_ADMIN_PASSWORD}
      JOOMLA_ADMIN_EMAIL: ${JOOMLA_ADMIN_EMAIL}
    volumes:
      # - ./joomla_data:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - joomla_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${JOOMLA_DB_NAME}
      MYSQL_USER: ${JOOMLA_DB_USER}
      MYSQL_PASSWORD: ${JOOMLA_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./data/${ENVIRONMENT}/:/docker-entrypoint-initdb.d/
    networks:
      - joomla_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8010:80"
    depends_on:
    - db
    environment:
      PMA_HOST: "db:3306"
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    networks:
      - joomla_network

  mailhog:
    image: mailhog/mailhog
    restart: always
    environment:
      MH_AUTH_FILE: /mailhog.auth
      # MH_MAILDIR_PATH: /data
      MH_STORAGE: maildir
    volumes:
      - ./config/mailhog.auth:/mailhog.auth:ro
      # - ./data:/data:rw
    ports:
      - "1027:1025" #127.0.0.1:1025:1025  
      - "8027:8025"
    networks:
      - joomla_network

volumes:
  joomla_data:
  db_data:

networks:
  joomla_network:
